spring:
  profiles: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/prova
    username: root
    password:
prop:
  yaml: MYSQLYaml
---
spring:
  profiles: docker
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://adefazio-mysql:3306/prova
    username: root
    password:
prop:
  yaml: DockerYaml
